collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3602291
  brandStrength: 0.849087
  lightness: 0.9876477
  brandColors:
    - '#FFFFFF'
    - '#D6D0C7'
    - '#160E0C'
    - '#6E655C'
    - '#FB6749'
  rhythmicContrast: 0.1413208
typography_spectrum: 0.1183292
layout_spectrum: 0.05746506
name: ArchiBuild
